feat: run esm and cjs test in parallel
Signed-off-by: Pritam Singh <pkspritam16@gmail.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -34,10 +34,23 @@ jobs:
         run: npm run build
 
   integration-tests:
-    name: "Integration Tests"
+    name: Integration Tests (${{ matrix.name }})
     runs-on: ubuntu-latest
     needs: build
-    
+
+    env:
+      ORACLE_TESTS: "DIDModule|DID Key Operations|OracleModule|ResourceModule"
+
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - name: esm
+            test_directory: esm
+
+          - name: cjs
+            test_directory: cjs
+
     steps:
       - uses: actions/checkout@v5
 
@@ -55,8 +68,34 @@ jobs:
       - name: "Clean install dependencies"
         run: npm ci
 
-      - name: Run Tests
-        run: bash .github/scripts/integration-tests.sh
+      - name: Run oracle independent tests
+        working-directory: ${{ matrix.test_directory }}
+        run: npm run test -- --testNamePattern="^(?!${ORACLE_TESTS})"
+      
+      - name: Wait for WMA calculation
+        working-directory: localnet
+        shell: bash
+        run: |
+          set -euo pipefail
+
+          WAIT_TIME=240 # seconds
+          INTERVAL=20
+
+          echo "Waiting for WMA to be available..."
+
+          while ! docker compose exec cheqd cheqd-noded q oracle wma CHEQ >/dev/null 2>&1; do
+            if [ "$WAIT_TIME" -le 0 ]; then
+              echo "Unable to compute WMA within timeout"
+              exit 1
+            fi
+
+            sleep "$INTERVAL"
+            WAIT_TIME=$((WAIT_TIME - INTERVAL))
+          done
+
+      - name: Run oracle dependent tests
+        working-directory: ${{ matrix.test_directory }}
+        run: npm run test -- --testNamePattern="(${ORACLE_TESTS})"
 
   import-tests:
     name: "Import Tests"
