ci: define integration-tests with strategy
Signed-off-by: Pritam Singh <pkspritam16@gmail.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -34,9 +34,25 @@ jobs:
         run: npm run build
 
   integration-tests:
-    name: "Integration Tests"
+    name: Integration Tests (${{ matrix.name }})
     runs-on: ubuntu-latest
     needs: build
+
+    env:
+      ORACLE_TESTS: "DIDModule|DID Key Operations|OracleModule|ResourceModule"
+
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - name: Non-Oracle
+            test_pattern: "^(?!${ORACLE_TESTS})"
+            needs_oracle_wait: false
+
+          - name: Oracle
+            test_pattern: "(${ORACLE_TESTS})"
+            needs_oracle_wait: true
+
 
     steps:
       - uses: actions/checkout@v5
@@ -55,8 +71,36 @@ jobs:
       - name: "Clean install dependencies"
         run: npm ci
 
-      - name: Run Tests
-        run: npm test
+      - name: Wait for WMA calculation
+        working-directory: localnet
+        if: matrix.needs_oracle_wait
+        shell: bash
+        run: |
+          set -euo pipefail
+
+          WAIT_TIME=240 # seconds
+          INTERVAL=20
+
+          echo "Waiting for WMA to be available..."
+
+          while ! docker compose exec cheqd cheqd-noded q oracle wma CHEQ >/dev/null 2>&1; do
+            if [ "$WAIT_TIME" -le 0 ]; then
+              echo "Unable to compute WMA within timeout"
+              exit 1
+            fi
+
+            sleep "$INTERVAL"
+            WAIT_TIME=$((WAIT_TIME - INTERVAL))
+          done
+
+      - name: Run ems package tests
+        working-directory: esm
+        run: npm run test -- --testNamePattern="${{ matrix.test_pattern }}"
+
+      - name: Run cjs package tests
+        working-directory: cjs
+        run: npm run test -- --testNamePattern="${{ matrix.test_pattern }}"
+
 
   import-tests:
     name: "Import Tests"
